plugins {
    id 'java-library'
    id 'io.freefair.lombok'
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management'
    id 'jacoco'
}

group = 'co.com.dgallego58'
version = '1.0.0'

repositories {
    mavenCentral()
}
jar{
    enabled = true
    archiveFileName = "${project.parent.name}-${project.name}-${version}.${archiveExtension.get()}"
}

bootJar{
    enabled = false
}


dependencies {
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}
