plugins {
    id 'spring-boot'
}

bootJar{
    enabled = true
    archiveFileName = "${project.parent.name}-${project.name}-bootjar-${version}.${archiveExtension.get()}"
}


dependencies {

    implementation project(':model')
    implementation project(':usecase')

    implementation project(':utils')
    implementation project(':apirest')
    implementation project(':database')
    implementation project(':security')

}

