spring:
  application:
    name: test-registry-user
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
  config:
    import: classpath:secured-paths.yml
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
